[tool.poetry]
name = "saenopy"
version = "0.7.4"
description = "Semi-elastic fiber optimisation in python."
authors = ["rgerum <14153051+rgerum@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "saenopy"}]


[tool.poetry.dependencies]
python = "^3.8"
numpy = "^1.23.4"
scipy = "^1.9.3"
tqdm = "^4.64.1"
qimage2ndarray = "^1.9.0"
natsort = "^8.2.0"
pyvista = "^0.37.0"
pyvistaqt = "^0.9.0"
imagecodecs = "^2022.9.26"
openpiv = "^0.24.2"
pyqt5 = "^5.15.7"
qtawesome = "^1.2.1"
jointforces = "^1.0.1"
numba = "^0.56.4"


[tool.poetry.scripts]
saenopy = "saenopy.gui_master:main"


[tool.poetry.group.docs.dependencies]
sphinx-rtd-theme = "^1.1.1"
nbsphinx = "^0.8.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
