name: Create Linux PyInstaller .exe

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: build exe with pyinstaller
      shell: bash
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt      
        pip install pyinstaller
        pyinstaller --clean -y --dist output/saenopy_run --onefile saenopy/gui_master.py 

    - uses: actions/upload-artifact@v2
      with:
        name: name-of-artifact
        path: output/saenopy_run
